Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"


  config.vm.network "forwarded_port", guest: 3306, host: 3406, auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 8180, auto_correct: true
  config.vm.network "forwarded_port", guest: 5672, host: 5672, auto_correct: true
  config.vm.network "forwarded_port", guest: 15672, host: 15672, auto_correct: true
  config.vm.network "forwarded_port", guest: 3128, host: 33128, auto_correct: true
  
  config.vm.define "clspeed" do |clspeed|
  end

  config.vm.provision :ansible do |ansible|
     ansible.playbook = "playbook.yml"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

end
