FROM debian
RUN apt-get update && apt-get install -y wget lsb-release
RUN wget https://dev.mysql.com/get/mysql-apt-config_0.8.4-1_all.deb
RUN dpkg -i mysql-apt-config_0.8.4-1_all.deb
#RUN apt-get update 

